import { Insumo } from "../../mock-core/models/insumo.model";

export let insumos: Insumo[] = [
    {id: '1', nombreInsumo: 'Tomate', marca:'Rocky',  tipoInsumo:"Alimento", costo: 1400, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '2', nombreInsumo: 'Palta', marca:'Paltahass',  tipoInsumo:"Alimento", costo: 2000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '3', nombreInsumo: 'Lechuga Española', marca:'Dole',  tipoInsumo:"Alimento", costo: 990, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '4', nombreInsumo: 'Pollo', marca:'Super Pollo',  tipoInsumo:"Alimento", costo: 2190, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '5', nombreInsumo: 'Papa', marca:'Decaba',  tipoInsumo:"Alimento", costo: 1125, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '6', nombreInsumo: 'Queso ricotta', marca:'Quillayes',  tipoInsumo:"Alimento", costo: 2990, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '7', nombreInsumo: 'Longaniza artesanal 1k', marca:'Llanquihue',  tipoInsumo:"Alimento", costo: 7899, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '8', nombreInsumo: 'Spaghetti', marca:'Lucchetti',  tipoInsumo:"Alimento", costo: 1600, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '9', nombreInsumo: 'Pan Frica', marca:'Castaño',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '10', nombreInsumo: 'Hamburguesa', marca:'La Crianza',  tipoInsumo:"Alimento", costo: 10000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '11', nombreInsumo: 'Mayonesa', marca:'Hellmans',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '12', nombreInsumo: 'Aceite', marca:'Miraflores',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Litro', cantidad: 10},
    {id: '13', nombreInsumo: 'Vinagre', marca:'Miraflores',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Litro', cantidad: 10},
    {id: '14', nombreInsumo: 'Limon', marca:'Dole',  tipoInsumo:"Alimento", costo: 500, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '15', nombreInsumo: 'Sal', marca:'Lobos',  tipoInsumo:"Alimento", costo: 500, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '16', nombreInsumo: 'Crutones', marca:'Castaño',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '17', nombreInsumo: 'Pimenton Paprika', marca:'Gourmet',  tipoInsumo:"Alimento", costo: 5000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '18', nombreInsumo: 'Asado de tira', marca:'El Buen Corte',  tipoInsumo:"Alimento", costo: 8000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '19', nombreInsumo: 'Cebolla', marca:'Lomar',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '20', nombreInsumo: 'Ajo Polvo', marca:'Lomar',  tipoInsumo:"Alimento", costo: 4000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '21', nombreInsumo: 'Papa', marca:'Lomar',  tipoInsumo:"Alimento", costo: 5000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '22', nombreInsumo: 'Zanahoria', marca:'Lomar',  tipoInsumo:"Alimento", costo: 1000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '23', nombreInsumo: 'Arroz', marca:'Tucapel',  tipoInsumo:"Alimento", costo: 1350, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '24', nombreInsumo: 'Perejil', marca:'Lomar',  tipoInsumo:"Alimento", costo: 4000, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '25', nombreInsumo: 'Zapallo Camote', marca:'Lomar',  tipoInsumo:"Alimento", costo: 1400, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '26', nombreInsumo: 'Choclo', marca:'Lomar',  tipoInsumo:"Alimento", costo: 1500, unidadMedida: 'Kilogramo', cantidad: 10},
    {id: '27', nombreInsumo: 'Caldo Pollo', marca:'Maggi',  tipoInsumo:"Alimento", costo: 7000, unidadMedida: 'Kilogramo', cantidad: 10},
];